<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['base_url']             = 'http://localhost/explore/';
$config['index_page']           = '';          // clean URLs via .htaccess
$config['uri_protocol']         = 'AUTO';
$config['url_suffix']           = '';
$config['language']             = 'english';
$config['charset']              = 'UTF-8';
$config['enable_hooks']         = FALSE;
$config['subclass_prefix']      = 'MY_';
$config['permitted_uri_chars']  = 'a-z 0-9~%.:_\-';
$config['allow_get_array']      = TRUE;
$config['enable_query_strings'] = FALSE;
$config['log_threshold']        = 0;
$config['log_path']             = '';
$config['log_file_extension']   = '';
$config['log_date_format']      = 'Y-m-d H:i:s';
$config['cache_path']           = '';
$config['encryption_key']       = 'ET_s3cr3t_K3y_2024!';
$config['sess_driver']          = 'database';
$config['sess_cookie_name']     = 'et_session';
$config['sess_expiration']      = 7200;
$config['sess_save_path']       = 'ci_sessions';
$config['sess_match_ip']        = FALSE;
$config['sess_time_to_update']  = 300;
$config['sess_regenerate_destroy'] = FALSE;
$config['cookie_prefix']        = '';
$config['cookie_domain']        = '';
$config['cookie_path']          = '/';
$config['cookie_secure']        = FALSE;
$config['cookie_httponly']      = FALSE;
$config['csrf_protection']      = TRUE;
$config['csrf_token_name']      = 'csrf_token';
$config['csrf_cookie_name']     = 'csrf_cookie';
$config['csrf_expire']          = 7200;
$config['csrf_regenerate']      = FALSE; // Keep token stable for AJAX calls
$config['csrf_exclude_uris']    = array();
$config['compress_output']      = FALSE;
$config['time_reference']       = 'local';
$config['rewrite_short_tags']   = FALSE;
$config['error_views_path']     = '';
